AWSTemplateFormatVersion: '2010-09-09'
Description: >
  AWS CloudFormation template to create an EC2 instance with an associated security group.

Resources:
  # Resource for the EC2 Security Group
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP access
      SecurityGroupIngress:
        # Allow inbound SSH access from any IP address
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

  # Resource for the EC2 Instance
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0049e4b5ba14b6d36  # Example AMI for Amazon Linux 2 in us-east-1
      KeyName: croma-aish-4
      # Associate the security group with the EC2 instance
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: 1.30pm-sys
